In [1]:
# Numpy :- Numerical Python  . In this we deal with Arrays and Matrix

In [31]:
import numpy as np

In [32]:
l =[1,2,3,4]

In [33]:
ar = np.array(l)

In [34]:
ar

array([1, 2, 3, 4])

In [35]:
type(ar)

numpy.ndarray

In [36]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [37]:
np.asarray(l)

array([1, 2, 3, 4])

In [38]:
a = [2,3,4]

In [39]:
np.asanyarray(a)

array([2, 3, 4])

In [40]:
b = np.matrix(l)

In [41]:
b  # matrix by default 2-D .

matrix([[1, 2, 3, 4]])

In [42]:
np.asanyarray(b)  # .asanyarray() can't convert matrix into array, because Matrix is also a subset of an array.

matrix([[1, 2, 3, 4]])

In [43]:
a = np.array(l)

In [44]:
a

array([1, 2, 3, 4])

In [45]:
c = a

In [46]:
c


array([1, 2, 3, 4])

In [47]:
c[0] = 100

In [48]:
c

array([100,   2,   3,   4])

In [49]:
a

array([100,   2,   3,   4])

In [50]:
d = np.copy(a)  # This is called deep copy

In [51]:
d

array([100,   2,   3,   4])

In [52]:
a

array([100,   2,   3,   4])

In [53]:
a[1] = 400

In [54]:
a

array([100, 400,   3,   4])

In [55]:
# At the end of the day , We will generate the array. So, in Numpy a lot of functions included which helps to generate a different
# different dimensions of arrays.

In [56]:
np.fromfunction(lambda i,j : i== j,(3,3)) # Now, this function will generate 3X3 dim. data.

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [57]:
np.fromfunction(lambda i,j : i*j,(3,3)) # This formfunction is used to generating the arrays.

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [58]:
iterable = (i*i for i in range(5))

In [59]:
np.fromiter(iterable,float)  # generating array by using iterables.

array([ 0.,  1.,  4.,  9., 16.])

In [60]:
np.fromstring('234 235' , sep = ' ') # generating arrays by using strings, and seprated from space ' '


array([234., 235.])

# Numpy - Data Types

In [61]:
l = [2,3,4,5,6]

In [62]:
ar = np.array(l)

In [63]:
ar

array([2, 3, 4, 5, 6])

In [64]:
ar.ndim  # To know the dimesion  by  .ndim

1

In [65]:
ar2 = np.array([[1,2,3,4],[2,3,4,5]])

In [66]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [67]:
ar2.ndim

2

In [68]:
ar.size  # To know the size of array(no. of elements in an array)

5

In [69]:
ar.shape  # To know the row and columns of the array  Ex:- (row,column)

(5,)

In [70]:
ar2.shape

(2, 4)

In [71]:
ar.dtype  # To know the type of data .

dtype('int64')

In [72]:
ar2.dtype

dtype('int64')

In [73]:
ar22 = np.array([(1.4,45,45),(23,45,66)])

In [74]:
ar22  # It will change the data type of all the elements bcoz, Float have more space.

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [75]:
ar22.dtype

dtype('float64')

In [76]:
list(range(5))  # Range function always allow integers not floating point numbers.

[0, 1, 2, 3, 4]

In [77]:
# But in Numpy , This provision has included 
np.arange(2.3,5.6,.3)  # We can jump also.

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [78]:
list(np.arange(2.3,5.6,.3))  # converting array to list.

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [79]:
np.linspace(1,5,10) # Here linspace takes a line 1 to 5 and divided into 10 equal space. It's also a data generator function

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [80]:
np.zeros(5)  # generating array having zero value with size 5

array([0., 0., 0., 0., 0.])

In [81]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [82]:
# We  can generate 4-D and more but can't viualize in pictorial format

ar4 = np.zeros((3,4,2,3))

In [83]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [84]:
ar4.ndim   # This is 4-Dimensional but can't visualize graphically

4

In [85]:
np.ones(4)

array([1., 1., 1., 1.])

In [86]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [87]:
on = np.ones((2,3,2))

In [88]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [89]:
np.empty((3,5)) #Produced empty array.

array([[4.65691887e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.32404027e-322]])

In [90]:
np.eye(4)  # identity matrix


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [91]:
np.linspace(2,4,20)  # generated data

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [92]:
np.logspace(2,5,10) # generate data between 2,5 and needed data 10 . with their log(by default base 10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [93]:
np.logspace(2,5,10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

# Famous functions:- 

In [94]:
arr = np.random.randn(3,4) # It will generate 3X4 data randomly (It returns a sample from the "standard normal" distribution.

In [95]:
import pandas as pd

In [96]:
pd.DataFrame(arr)  # converted into DataFrame

0         1         2         3
0 -0.027846 -0.406233 -0.359075 -0.691377
1 -0.525243  0.823550  0.644366  0.699316
2  0.655108 -0.778545 -0.573745 -0.731716

In [97]:
np.random.rand(3,4) # Random data

array([[0.53065665, 0.55138212, 0.86063019, 0.21683332],
       [0.88905858, 0.87704883, 0.01998344, 0.17205872],
       [0.96078516, 0.21077836, 0.09969525, 0.29028391]])

In [98]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('test.csv') 
# generate int. data randomly . Also can be convert into DataFrame and can be stored into the csv. file.

In [99]:
arr

array([[-0.02784642, -0.40623264, -0.35907523, -0.69137718],
       [-0.52524335,  0.82355048,  0.64436554,  0.69931618],
       [ 0.65510841, -0.77854515, -0.57374481, -0.73171605]])

In [100]:
arr.reshape(6,2) # Re-arranged above data into 6X2

array([[-0.02784642, -0.40623264],
       [-0.35907523, -0.69137718],
       [-0.52524335,  0.82355048],
       [ 0.64436554,  0.69931618],
       [ 0.65510841, -0.77854515],
       [-0.57374481, -0.73171605]])

In [101]:
arr.reshape(6,3)  # This will not work bcoz, data is whole not a  fractional

ValueError: cannot reshape array of size 12 into shape (6,3)

In [102]:

arr1 = arr.reshape(6,-1) # Bcoz, It'll understand itself one dim. is 6 and other is 2

In [103]:
arr1

array([[-0.02784642, -0.40623264],
       [-0.35907523, -0.69137718],
       [-0.52524335,  0.82355048],
       [ 0.64436554,  0.69931618],
       [ 0.65510841, -0.77854515],
       [-0.57374481, -0.73171605]])

In [104]:
arr1[1][1]  # Fetching first column. With the help of indexing and slicing we can access any data.

-0.691377180723896

In [105]:
arr1[2:5,1]

array([ 0.82355048,  0.69931618, -0.77854515])

In [106]:
arr = np.random.randint(1,100,(5,5))

In [107]:
arr

array([[37, 42, 60,  9, 15],
       [ 1, 61, 22,  5, 50],
       [13, 64,  7, 97, 59],
       [24, 25, 38, 20, 13],
       [13, 94, 34, 61, 26]])

In [108]:
arr[arr>50]

array([60, 61, 64, 97, 59, 94, 61])

In [109]:
arr

array([[37, 42, 60,  9, 15],
       [ 1, 61, 22,  5, 50],
       [13, 64,  7, 97, 59],
       [24, 25, 38, 20, 13],
       [13, 94, 34, 61, 26]])

In [110]:
arr[2:4 , 1:3] # fetching data from any place

array([[64,  7],
       [25, 38]])

In [111]:
arr[0][0] = 5000

In [112]:
arr

array([[5000,   42,   60,    9,   15],
       [   1,   61,   22,    5,   50],
       [  13,   64,    7,   97,   59],
       [  24,   25,   38,   20,   13],
       [  13,   94,   34,   61,   26]])

In [116]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [117]:
arr1

array([[2, 1, 2],
       [2, 1, 1],
       [1, 2, 1]])

In [118]:
arr1 + arr2

array([[4, 2, 3],
       [3, 2, 3],
       [3, 4, 2]])

In [120]:
arr1*arr2  #This is simple index multiplication not a matrix multiplication.

array([[4, 1, 2],
       [2, 1, 2],
       [2, 4, 1]])

#Matrix multiplication

In [122]:
arr1

array([[2, 1, 2],
       [2, 1, 1],
       [1, 2, 1]])

In [123]:
arr2

array([[2, 1, 1],
       [1, 1, 2],
       [2, 2, 1]])

In [125]:
arr1@arr2  # Here '@' return the matrix multiplication of two arrays.

array([[9, 7, 6],
       [7, 5, 5],
       [6, 5, 6]])

In [127]:
arr1/0  # Generally in python it gives 'error'. But, in Numpy package, It will return 'Infinity'

/tmp/ipykernel_90/3289283540.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0  # Generally in python it gives 'error'. But, in Numpy package, It will return 'Infinity'


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [128]:
arr1+100 # Adding 100 to all elements of an array

array([[102, 101, 102],
       [102, 101, 101],
       [101, 102, 101]])

In [130]:
arr1**2  # squaring each and every elements of an array.

array([[4, 1, 4],
       [4, 1, 1],
       [1, 4, 1]])

 # Numpy - Broadcasting.

In [132]:
arr = np.zeros((4,4))

In [133]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [134]:
row = np.array([1,2,3,4]) # This array will not transpose.

In [135]:
row

array([1, 2, 3, 4])

In [137]:
arr + row  # This is row-wise broadcasting.

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [139]:
col = np.array([[1,2,3,4]])

In [143]:
col.T  # 'T' is used to transpose of matrix

array([[1],
       [2],
       [3],
       [4]])

In [145]:
col.T + arr  # This is column-wise broadcasting.

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [148]:
arr1 = np.random.randint(1,4,(3,4))

In [149]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.        , 1.73205081],
       [1.73205081, 1.41421356, 1.73205081, 1.41421356],
       [1.73205081, 1.73205081, 1.        , 1.73205081]])

In [150]:
np.exp(arr1)

array([[ 7.3890561 ,  2.71828183,  2.71828183, 20.08553692],
       [20.08553692,  7.3890561 , 20.08553692,  7.3890561 ],
       [20.08553692, 20.08553692,  2.71828183, 20.08553692]])

In [151]:
np.log10(arr1)

array([[0.30103   , 0.        , 0.        , 0.47712125],
       [0.47712125, 0.30103   , 0.47712125, 0.30103   ],
       [0.47712125, 0.47712125, 0.        , 0.47712125]])